# Generated by Django 4.0.4 on 2022-05-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time',
            new_name='cooking_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='content',
            new_name='instructions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
    ]
