# Generated by Django 3.2 on 2022-06-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='Description', max_length=255),
            preserve_default=False,
        ),
    ]
