# Generated by Django 4.0.4 on 2022-05-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='slug',
        ),
    ]
