# Generated by Django 4.0.4 on 2022-05-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_category_unit_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(default={models.CharField(max_length=200, unique=True)}, max_length=200, unique=True),
        ),
    ]
