# Generated by Django 4.0.4 on 2022-05-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_ingredient_unit_reciperequirement_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperequirement',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='reciperequirement',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.ingredient'),
        ),
        migrations.RemoveField(
            model_name='reciperequirement',
            name='unit',
        ),
        migrations.AddField(
            model_name='reciperequirement',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.unit'),
        ),
    ]
