# Generated by Django 4.0.4 on 2022-05-22 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_reciperequirement_alter_ingredient_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('unit', models.IntegerField(choices=[(0, 'g'), (1, 'kg'), (2, 'cups'), (3, 'ml')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='recipe.recipe'),
        ),
        migrations.DeleteModel(
            name='RecipeRequirement',
        ),
        migrations.AddField(
            model_name='ingredientmeta',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='recipe.ingredient'),
        ),
    ]
