# Generated by Django 3.2 on 2022-05-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_instructions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructions',
            old_name='description',
            new_name='step',
        ),
        migrations.RemoveField(
            model_name='instructions',
            name='step_no',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
